# configuration for https://ohi-science.nceas.ucsb.edu/pol
study_area:       Poland
git_owner:        OHI-Science
git_repo:         pol
git_slug:         OHI-Science/pol
git_url:          https://github.com/OHI-Science/pol
app_url:          http://ohi-science.nceas.ucsb.edu/pol
default_branch:   published
default_scenario: subcountry2014
debug:            False
last_updated:     2015-05-20
ohicore_app:
  git_owner: ohi-science
  git_repo: ohicore
  git_branch: dev
  git_commit: 41ea1726ba08bf1727d6fca34949db12b9d9fa1c

tabs_hide:        
- Calculate
- Report

